### PR TITLE
python3 support

### LINKED ISSUE #48: python3 support plan?
Hi @dlecocq

Thanks for this python lib! It helps a lot. 👍 
And any thoughts about python3 support?

Thanks,
Phus

### PR DESCRIPTION
**Pull request by asottile**
Resolves #48

### CODE REVIEW

**Comment by asottile** [comment]
tbh, no idea if this works in python3 -- however it passes the tests

**Comment by asottile** [comment]
we're using this successfully in production, can confirm it works

**Comment by asottile** [comment]
@dlecocq any chance of a review here? we're using this successfully in production at lyft and it's working well :)

**Comment by dlecocq** [comment]
@asottile - Do y'all need a version bump and a pypi release?

**Comment by asottile** [comment]
that would be great!

**Comment by dlecocq** [comment]
0.1.12 should be released and ready to use!

**Comment by asottile** [comment]
awesome! thanks a ton for this \o/

**Comment by dlecocq** [comment]
Thanks for your contribution!

**Pull request merged**
